/*
 * Created on 19 nov 2016 ( Time 11:55:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.informe.jpa;

import java.io.Serializable;
import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "v_cant_prod_vendidos"
 *
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name="v_cant_prod_vendidos", catalog="salon_de_ventas" )
public class VCantProdVendidosEntity implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------   
   
    @Column(name="nombre", nullable=false, length=90)
		@NotNull
			@Size(max = 90)
	    private String     nombre       ;

    @Column(name="cantidad")
		    private BigDecimal cantidad     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VCantProdVendidosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : cantidad ( DECIMAL ) 
    public void setCantidad( BigDecimal cantidad ) {
        this.cantidad = cantidad;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(cantidad);
        return sb.toString(); 
    } 

}
