
/*
 * Created on 9 oct 2016 ( Time 02:32:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.mock;

import java.util.LinkedList;
import java.util.List;

import org.salondeventas.server.modelo.jpa.LineadeventaEntity;
import org.salondeventas.server.mock.tool.MockValues;

public class LineadeventaEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public LineadeventaEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger(), mockValues.nextInteger(), mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public LineadeventaEntity createInstance( Integer idlineadeventa, Integer idproducto, Integer idventa ) {
		LineadeventaEntity entity = new LineadeventaEntity();
		// Init Primary Key fields
		entity.setIdlineadeventa( idlineadeventa) ;
		entity.setIdproducto( idproducto) ;
		entity.setIdventa( idventa) ;
		// Init Data fields
		// Init Link fields (if any)
		// setVenta( TODO ) ; // Venta 
		// setProducto( TODO ) ; // Producto 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<LineadeventaEntity> createList(int count) {
		List<LineadeventaEntity> list = new LinkedList<LineadeventaEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
