
/*
 * Created on 9 oct 2016 ( Time 02:32:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.mock;

import java.util.LinkedList;
import java.util.List;

import org.salondeventas.server.modelo.jpa.PrecioproductoEntity;
import org.salondeventas.server.mock.tool.MockValues;

public class PrecioproductoEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PrecioproductoEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger(), mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PrecioproductoEntity createInstance( Integer idprecioproducto, Integer idproducto ) {
		PrecioproductoEntity entity = new PrecioproductoEntity();
		// Init Primary Key fields
		entity.setIdprecioproducto( idprecioproducto) ;
		entity.setIdproducto( idproducto) ;
		// Init Data fields
		entity.setFecha( mockValues.nextDate() ) ; // java.util.Date 
		entity.setImporte( mockValues.nextBigDecimal() ) ; // java.math.BigDecimal 
		// Init Link fields (if any)
		// setProducto( TODO ) ; // Producto 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PrecioproductoEntity> createList(int count) {
		List<PrecioproductoEntity> list = new LinkedList<PrecioproductoEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
