
/*
 * Created on 9 oct 2016 ( Time 02:32:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.mock;

import java.util.LinkedList;
import java.util.List;

import org.salondeventas.server.modelo.jpa.ProductoEntity;
import org.salondeventas.server.mock.tool.MockValues;

public class ProductoEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ProductoEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ProductoEntity createInstance( Integer idproducto ) {
		ProductoEntity entity = new ProductoEntity();
		// Init Primary Key fields
		entity.setIdproducto( idproducto) ;
		// Init Data fields
		entity.setDetalle( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setNombre( mockValues.nextString(90) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfPrecioproducto( TODO ) ; // List<Precioproducto> 
		// setListOfLineadeventa( TODO ) ; // List<Lineadeventa> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ProductoEntity> createList(int count) {
		List<ProductoEntity> list = new LinkedList<ProductoEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
