
/*
 * Created on 9 oct 2016 ( Time 02:32:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.mock;

import java.util.LinkedList;
import java.util.List;

import org.salondeventas.server.modelo.jpa.UsuarioEntity;
import org.salondeventas.server.mock.tool.MockValues;

public class UsuarioEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UsuarioEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UsuarioEntity createInstance( Integer idusuario ) {
		UsuarioEntity entity = new UsuarioEntity();
		// Init Primary Key fields
		entity.setIdusuario( idusuario) ;
		// Init Data fields
		entity.setNombre( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setClave( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UsuarioEntity> createList(int count) {
		List<UsuarioEntity> list = new LinkedList<UsuarioEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
