
/*
 * Created on 9 oct 2016 ( Time 02:32:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.mock;

import java.util.LinkedList;
import java.util.List;

import org.salondeventas.server.modelo.jpa.VentaEntity;
import org.salondeventas.server.mock.tool.MockValues;

public class VentaEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public VentaEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public VentaEntity createInstance( Integer idventa ) {
		VentaEntity entity = new VentaEntity();
		// Init Primary Key fields
		entity.setIdventa( idventa) ;
		// Init Data fields
		entity.setFecha( mockValues.nextDate() ) ; // java.util.Date 
		entity.setFechaPago( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setListOfLineadeventa( TODO ) ; // List<Lineadeventa> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<VentaEntity> createList(int count) {
		List<VentaEntity> list = new LinkedList<VentaEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
