/*
 * Created on 31 oct 2016 ( Time 11:50:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

import javax.validation.constraints.*;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "configuracion"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="configuracion", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ConfiguracionEntity.countAll", query="SELECT COUNT(x) FROM ConfiguracionEntity x" )
} )
public class ConfiguracionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idconfiguracion", nullable=false)
    private Integer    idconfiguracion ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@NotNull
	@Size(max = 45)
    @Column(name="codigo", nullable=false, length=45)
    private String     codigo       ;

	@NotNull
	@Size(max = 90)
    @Column(name="nombre", nullable=false, length=90)
    private String     nombre       ;

	@Size(max = 255)
    @Column(name="descripcion", length=255)
    private String     descripcion  ;

	@Size(max = 8000)
    @Column(name="valor", length=8000)
    private String     valor        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ConfiguracionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdconfiguracion( Integer idconfiguracion ) {
        this.idconfiguracion = idconfiguracion ;
    }
    public Integer getIdconfiguracion() {
        return this.idconfiguracion;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : codigo ( VARCHAR ) 
    public void setCodigo( String codigo ) {
        this.codigo = codigo;
    }
    public String getCodigo() {
        return this.codigo;
    }

    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : descripcion ( VARCHAR ) 
    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    //--- DATABASE MAPPING : valor ( VARCHAR ) 
    public void setValor( String valor ) {
        this.valor = valor;
    }
    public String getValor() {
        return this.valor;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idconfiguracion);
        sb.append("]:"); 
        sb.append(codigo);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(valor);
        return sb.toString(); 
    } 

}
