/*
 * Created on 16 sep 2016 ( Time 15:30:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "empresa"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="empresa", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EmpresaEntity.countAll", query="SELECT COUNT(x) FROM EmpresaEntity x" )
} )
public class EmpresaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="idEmpresa", nullable=false)
	@GeneratedValue(strategy=GenerationType.AUTO)
    private Integer    idempresa    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nombre", length=90)
    private String     nombre       ;

    @Column(name="descripcion", length=255)
    private String     descripcion  ;

    @Lob
    @Column(name="logo")
    private byte[]     logo         ;

    @Column(name="direccion", length=45)
    private String     direccion    ;

    @Column(name="telefono", length=45)
    private String     telefono     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EmpresaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdempresa( Integer idempresa ) {
        this.idempresa = idempresa ;
    }
    public Integer getIdempresa() {
        return this.idempresa;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : descripcion ( VARCHAR ) 
    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    //--- DATABASE MAPPING : logo ( BLOB ) 
    public void setLogo( byte[] logo ) {
        this.logo = logo;
    }
    public byte[] getLogo() {
        return this.logo;
    }

    //--- DATABASE MAPPING : direccion ( VARCHAR ) 
    public void setDireccion( String direccion ) {
        this.direccion = direccion;
    }
    public String getDireccion() {
        return this.direccion;
    }

    //--- DATABASE MAPPING : telefono ( VARCHAR ) 
    public void setTelefono( String telefono ) {
        this.telefono = telefono;
    }
    public String getTelefono() {
        return this.telefono;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idempresa);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(descripcion);
        // attribute 'logo' not usable (type = byte[])
        sb.append("|");
        sb.append(direccion);
        sb.append("|");
        sb.append(telefono);
        return sb.toString(); 
    } 

}
