/*
 * Created on 31 oct 2016 ( Time 11:50:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

import javax.validation.constraints.*;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "perfilespermisos"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="perfilespermisos", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PerfilespermisosEntity.countAll", query="SELECT COUNT(x) FROM PerfilespermisosEntity x" )
} )
public class PerfilespermisosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private PerfilespermisosEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PerfilespermisosEntity() {
		super();
		this.compositePrimaryKey = new PerfilespermisosEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdperfiles( Integer idperfiles ) {
        this.compositePrimaryKey.setIdperfiles( idperfiles ) ;
    }
    public Integer getIdperfiles() {
        return this.compositePrimaryKey.getIdperfiles() ;
    }
    public void setIdpermisos( String idpermisos ) {
        this.compositePrimaryKey.setIdpermisos( idpermisos ) ;
    }
    public String getIdpermisos() {
        return this.compositePrimaryKey.getIdpermisos() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
