/*
 * Created on 31 oct 2016 ( Time 11:50:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

import javax.validation.constraints.*;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "perfilespantallas"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="perfilespantallas", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PerfilespantallasEntity.countAll", query="SELECT COUNT(x) FROM PerfilespantallasEntity x" )
} )
public class PerfilespantallasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private PerfilespantallasEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PerfilespantallasEntity() {
		super();
		this.compositePrimaryKey = new PerfilespantallasEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdperfiles( Integer idperfiles ) {
        this.compositePrimaryKey.setIdperfiles( idperfiles ) ;
    }
    public Integer getIdperfiles() {
        return this.compositePrimaryKey.getIdperfiles() ;
    }
    public void setIdpantallas( Integer idpantallas ) {
        this.compositePrimaryKey.setIdpantallas( idpantallas ) ;
    }
    public Integer getIdpantallas() {
        return this.compositePrimaryKey.getIdpantallas() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
