/*
 * Created on 31 oct 2016 ( Time 11:50:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.modelo.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "PerfilespantallasEntity" ( stored in table "perfilespantallas" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class PerfilespantallasEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="idPerfiles", nullable=false)
    private Integer    idperfiles   ;
    
    @Column(name="idPantallas", nullable=false)
    private Integer    idpantallas  ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public PerfilespantallasEntityKey() {
        super();
    }

    public PerfilespantallasEntityKey( Integer idperfiles, Integer idpantallas ) {
        super();
        this.idperfiles = idperfiles ;
        this.idpantallas = idpantallas ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setIdperfiles( Integer value ) {
        this.idperfiles = value;
    }
    public Integer getIdperfiles() {
        return this.idperfiles;
    }

    public void setIdpantallas( Integer value ) {
        this.idpantallas = value;
    }
    public Integer getIdpantallas() {
        return this.idpantallas;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		PerfilespantallasEntityKey other = (PerfilespantallasEntityKey) obj; 
		//--- Attribute idperfiles
		if ( idperfiles == null ) { 
			if ( other.idperfiles != null ) 
				return false ; 
		} else if ( ! idperfiles.equals(other.idperfiles) ) 
			return false ; 
		//--- Attribute idpantallas
		if ( idpantallas == null ) { 
			if ( other.idpantallas != null ) 
				return false ; 
		} else if ( ! idpantallas.equals(other.idpantallas) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idperfiles
		result = prime * result + ((idperfiles == null) ? 0 : idperfiles.hashCode() ) ; 
		//--- Attribute idpantallas
		result = prime * result + ((idpantallas == null) ? 0 : idpantallas.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(idperfiles); 
		sb.append("|"); 
		sb.append(idpantallas); 
        return sb.toString();
    }
}
