/*
 * Created on 31 oct 2016 ( Time 11:50:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

import javax.validation.constraints.*;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "perfiles"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="perfiles", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PerfilesEntity.countAll", query="SELECT COUNT(x) FROM PerfilesEntity x" )
} )
public class PerfilesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idperfiles", nullable=false)
    private Integer    idperfiles   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@NotNull
	@Size(max = 90)
    @Column(name="nombre", nullable=false, length=90)
    private String     nombre       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToMany(mappedBy="listOfPerfiles", targetEntity=PantallaEntity.class)
    private List<PantallaEntity> listOfPantalla;

    @ManyToMany(targetEntity=PermisoEntity.class)
    @JoinTable(name="perfilespermisos", 
      joinColumns=@JoinColumn(name="idPerfiles", referencedColumnName="idperfiles"),
      inverseJoinColumns=@JoinColumn(name="idPermisos", referencedColumnName="idpermiso")
     ) 

    private List<PermisoEntity> listOfPermiso;

    @ManyToMany(targetEntity=UsuarioEntity.class)
    @JoinTable(name="usuarioperfiles", 
      joinColumns=@JoinColumn(name="idPerfil", referencedColumnName="idperfiles"),
      inverseJoinColumns=@JoinColumn(name="idUsuario", referencedColumnName="idUsuario")
     ) 

    private List<UsuarioEntity> listOfUsuario;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PerfilesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdperfiles( Integer idperfiles ) {
        this.idperfiles = idperfiles ;
    }
    public Integer getIdperfiles() {
        return this.idperfiles;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPantalla( List<PantallaEntity> listOfPantalla ) {
        this.listOfPantalla = listOfPantalla;
    }
    public List<PantallaEntity> getListOfPantalla() {
        return this.listOfPantalla;
    }

    public void setListOfPermiso( List<PermisoEntity> listOfPermiso ) {
        this.listOfPermiso = listOfPermiso;
    }
    public List<PermisoEntity> getListOfPermiso() {
        return this.listOfPermiso;
    }

    public void setListOfUsuario( List<UsuarioEntity> listOfUsuario ) {
        this.listOfUsuario = listOfUsuario;
    }
    public List<UsuarioEntity> getListOfUsuario() {
        return this.listOfUsuario;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idperfiles);
        sb.append("]:"); 
        sb.append(nombre);
        return sb.toString(); 
    } 

}
