/*
 * Created on 16 sep 2016 ( Time 15:30:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "precioproducto"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="precioproducto", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PrecioproductoEntity.countAll", query="SELECT COUNT(x) FROM PrecioproductoEntity x" )
} )
public class PrecioproductoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="idprecioproducto", nullable=false)
	@GeneratedValue(strategy=GenerationType.AUTO)
    private Integer    idprecioproducto ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false)
    private Date       fecha        ;

    @Column(name="importe", nullable=false)
    private BigDecimal importe      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="precioproducto", targetEntity=ProductoEntity.class)
    private List<ProductoEntity> listOfProducto;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PrecioproductoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdprecioproducto( Integer idprecioproducto ) {
        this.idprecioproducto = idprecioproducto ;
    }
    public Integer getIdprecioproducto() {
        return this.idprecioproducto;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : fecha ( DATETIME ) 
    public void setFecha( Date fecha ) {
        this.fecha = fecha;
    }
    public Date getFecha() {
        return this.fecha;
    }

    //--- DATABASE MAPPING : importe ( DECIMAL ) 
    public void setImporte( BigDecimal importe ) {
        this.importe = importe;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfProducto( List<ProductoEntity> listOfProducto ) {
        this.listOfProducto = listOfProducto;
    }
    public List<ProductoEntity> getListOfProducto() {
        return this.listOfProducto;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idprecioproducto);
        sb.append("]:"); 
        sb.append(fecha);
        sb.append("|");
        sb.append(importe);
        return sb.toString(); 
    } 

}
