/*
 * Created on 12 oct 2016 ( Time 21:59:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Persistent class for entity stored in table "producto"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="producto", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ProductoEntity.countAll", query="SELECT COUNT(x) FROM ProductoEntity x" )
} )
public class ProductoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idProducto", nullable=false)
    private Integer    idproducto   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
			@Size(max = 255)
	    @Column(name="detalle", length=255)
    private String     detalle      ;

		@NotNull
			@Size(max = 90)
	    @Column(name="nombre", nullable=false, length=90)
    private String     nombre       ;

			@Size(max = 90)
	    @Column(name="codBarras", length=90)
    private String     codbarras    ;

		    @Column(name="precio")
    private BigDecimal precio       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(fetch= FetchType.EAGER,mappedBy="producto", targetEntity=LineadeventaEntity.class)
    private List<LineadeventaEntity> listOfLineadeventa;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProductoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto ;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : detalle ( VARCHAR ) 
    public void setDetalle( String detalle ) {
        this.detalle = detalle;
    }
    public String getDetalle() {
        return this.detalle;
    }

    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : codBarras ( VARCHAR ) 
    public void setCodbarras( String codbarras ) {
        this.codbarras = codbarras;
    }
    public String getCodbarras() {
        return this.codbarras;
    }

    //--- DATABASE MAPPING : precio ( DECIMAL ) 
    public void setPrecio( BigDecimal precio ) {
        this.precio = precio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfLineadeventa( List<LineadeventaEntity> listOfLineadeventa ) {
        this.listOfLineadeventa = listOfLineadeventa;
    }
    public List<LineadeventaEntity> getListOfLineadeventa() {
        return this.listOfLineadeventa;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idproducto);
        sb.append("]:"); 
        sb.append(detalle);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(codbarras);
        sb.append("|");
        sb.append(precio);
        return sb.toString(); 
    } 

}
