/*
 * Created on 15 oct 2016 ( Time 22:40:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

import javax.validation.constraints.*;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "producto"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="producto", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ProductoEntity.countAll", query="SELECT COUNT(x) FROM ProductoEntity x" )
} )
public class ProductoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idProducto", nullable=false)
    private Integer    idproducto   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@NotNull
	@Size(max = 90)
    @Column(name="nombre", nullable=false, length=90)
    private String     nombre       ;

	@Size(max = 90)
    @Column(name="codBarras", length=90)
    private String     codbarras    ;

    @Column(name="minInventario")
    private Integer    mininventario ;

    @Column(name="precio")
    private BigDecimal precio       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @JsonIgnore
    @OneToMany(fetch= FetchType.EAGER,mappedBy="producto", targetEntity=LineadeventaEntity.class)
    private List<LineadeventaEntity> listOfLineadeventa;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProductoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto ;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : codBarras ( VARCHAR ) 
    public void setCodbarras( String codbarras ) {
        this.codbarras = codbarras;
    }
    public String getCodbarras() {
        return this.codbarras;
    }

    //--- DATABASE MAPPING : minInventario ( INT ) 
    public void setMininventario( Integer mininventario ) {
        this.mininventario = mininventario;
    }
    public Integer getMininventario() {
        return this.mininventario;
    }

    //--- DATABASE MAPPING : precio ( DECIMAL ) 
    public void setPrecio( BigDecimal precio ) {
        this.precio = precio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfLineadeventa( List<LineadeventaEntity> listOfLineadeventa ) {
        this.listOfLineadeventa = listOfLineadeventa;
    }
    public List<LineadeventaEntity> getListOfLineadeventa() {
        return this.listOfLineadeventa;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idproducto);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(codbarras);
        sb.append("|");
        sb.append(mininventario);
        sb.append("|");
        sb.append(precio);
        return sb.toString(); 
    } 

}
