/*
 * Created on 22 nov 2016 ( Time 09:10:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.modelo.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ProductoIngresoEntity" ( stored in table "producto_ingreso" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ProductoIngresoEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idproducto_ingreso", nullable=false)
	private Integer    idproductoIngreso ;
    
    @Column(name="idProducto", nullable=false)
	private Integer    idproducto   ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ProductoIngresoEntityKey() {
        super();
    }

    public ProductoIngresoEntityKey( Integer idproductoIngreso, Integer idproducto ) {
        super();
        this.idproductoIngreso = idproductoIngreso ;
        this.idproducto = idproducto ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setIdproductoIngreso( Integer value ) {
        this.idproductoIngreso = value;
    }
    public Integer getIdproductoIngreso() {
        return this.idproductoIngreso;
    }

    public void setIdproducto( Integer value ) {
        this.idproducto = value;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ProductoIngresoEntityKey other = (ProductoIngresoEntityKey) obj; 
		//--- Attribute idproductoIngreso
		if ( idproductoIngreso == null ) { 
			if ( other.idproductoIngreso != null ) 
				return false ; 
		} else if ( ! idproductoIngreso.equals(other.idproductoIngreso) ) 
			return false ; 
		//--- Attribute idproducto
		if ( idproducto == null ) { 
			if ( other.idproducto != null ) 
				return false ; 
		} else if ( ! idproducto.equals(other.idproducto) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idproductoIngreso
		result = prime * result + ((idproductoIngreso == null) ? 0 : idproductoIngreso.hashCode() ) ; 
		//--- Attribute idproducto
		result = prime * result + ((idproducto == null) ? 0 : idproducto.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(idproductoIngreso); 
		sb.append("|"); 
		sb.append(idproducto); 
        return sb.toString();
    }
}
