/*
 * Created on 31 oct 2016 ( Time 11:50:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

import javax.validation.constraints.*;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "usuarioperfiles"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="usuarioperfiles", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UsuarioperfilesEntity.countAll", query="SELECT COUNT(x) FROM UsuarioperfilesEntity x" )
} )
public class UsuarioperfilesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private UsuarioperfilesEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UsuarioperfilesEntity() {
		super();
		this.compositePrimaryKey = new UsuarioperfilesEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdusuario( Integer idusuario ) {
        this.compositePrimaryKey.setIdusuario( idusuario ) ;
    }
    public Integer getIdusuario() {
        return this.compositePrimaryKey.getIdusuario() ;
    }
    public void setIdperfil( Integer idperfil ) {
        this.compositePrimaryKey.setIdperfil( idperfil ) ;
    }
    public Integer getIdperfil() {
        return this.compositePrimaryKey.getIdperfil() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
