/*
 * Created on 5 oct 2016 ( Time 09:35:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.server.modelo.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "vproductos"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="vproductos", catalog="salon_de_ventas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="VproductosEntity.countAll", query="SELECT COUNT(x) FROM VproductosEntity x" )
} )
public class VproductosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Id
    @Column(name="idProducto", nullable=false)
    private Integer    idproducto   ;

    @Column(name="nombre", nullable=false, length=90)
    private String     nombre       ;

    @Column(name="detalle", length=255)
    private String     detalle      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha")
    private Date       fecha        ;

    @Column(name="importe")
    private BigDecimal importe      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VproductosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : idProducto ( INT ) 
    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }

    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : detalle ( VARCHAR ) 
    public void setDetalle( String detalle ) {
        this.detalle = detalle;
    }
    public String getDetalle() {
        return this.detalle;
    }

    //--- DATABASE MAPPING : fecha ( DATETIME ) 
    public void setFecha( Date fecha ) {
        this.fecha = fecha;
    }
    public Date getFecha() {
        return this.fecha;
    }

    //--- DATABASE MAPPING : importe ( DECIMAL ) 
    public void setImporte( BigDecimal importe ) {
        this.importe = importe;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(idproducto);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(detalle);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(importe);
        return sb.toString(); 
    } 

}
