/*
 * Created on 4 oct 2016 ( Time 09:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.persistence.services;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.PrecioproductoEntity;

/**
 * Basic persistence operations for entity "Precioproducto"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface PrecioproductoPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param precioproducto
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PrecioproductoEntity precioproducto) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idprecioproducto
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idprecioproducto) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param precioproducto
	 */
	public void insert(PrecioproductoEntity precioproducto) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idprecioproducto
	 * @return the entity loaded (or null if not found)
	 */
	public PrecioproductoEntity load(Integer idprecioproducto) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PrecioproductoEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PrecioproductoEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PrecioproductoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param precioproducto
	 * @return
	 */
	public PrecioproductoEntity save(PrecioproductoEntity precioproducto) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PrecioproductoEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
