/*
 * Created on 4 oct 2016 ( Time 09:46:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.persistence.services;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.VentaEntity;

/**
 * Basic persistence operations for entity "Venta"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface VentaPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param venta
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(VentaEntity venta) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idventa
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idventa) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param venta
	 */
	public void insert(VentaEntity venta) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idventa
	 * @return the entity loaded (or null if not found)
	 */
	public VentaEntity load(Integer idventa) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<VentaEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<VentaEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<VentaEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param venta
	 * @return
	 */
	public VentaEntity save(VentaEntity venta) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<VentaEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
