/*
 * Created on 4 oct 2016 ( Time 09:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.salondeventas.server.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.salondeventas.server.modelo.jpa.LineadeventaEntity;
import org.salondeventas.server.modelo.jpa.LineadeventaEntityKey;
import org.salondeventas.server.persistence.commons.jpa.GenericJpaService;
import org.salondeventas.server.persistence.commons.jpa.JpaOperation;
import org.salondeventas.server.persistence.services.LineadeventaPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Lineadeventa" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class LineadeventaPersistenceJPA extends GenericJpaService<LineadeventaEntity, LineadeventaEntityKey> implements LineadeventaPersistence {

	/**
	 * Constructor
	 */
	public LineadeventaPersistenceJPA() {
		super(LineadeventaEntity.class);
	}

	@Override
	public LineadeventaEntity load( Integer idlineadeventa, Integer idproducto, Integer idventa ) {
		// Build the composite key
		LineadeventaEntityKey key = new LineadeventaEntityKey( idlineadeventa, idproducto, idventa );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer idlineadeventa, Integer idproducto, Integer idventa ) {
		// Build the composite key
		LineadeventaEntityKey key = new LineadeventaEntityKey( idlineadeventa, idproducto, idventa );
		return super.delete( key );
	}

	@Override
	public boolean delete(LineadeventaEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			LineadeventaEntityKey key = new LineadeventaEntityKey( entity.getIdlineadeventa(), entity.getIdproducto(), entity.getIdventa() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("LineadeventaEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
