/*
 * Created on 4 oct 2016 ( Time 09:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.salondeventas.server.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.salondeventas.server.modelo.jpa.PrecioproductoEntity;
import org.salondeventas.server.persistence.commons.jpa.GenericJpaService;
import org.salondeventas.server.persistence.commons.jpa.JpaOperation;
import org.salondeventas.server.persistence.services.PrecioproductoPersistence;
import org.springframework.stereotype.Service;

/**
 * JPA implementation for basic persistence operations ( entity "Precioproducto" )
 * 
 * @author Telosys Tools Generator
 *
 */
@Service("precioproductoDao")
public class PrecioproductoPersistenceJPA extends GenericJpaService<PrecioproductoEntity, Integer> implements PrecioproductoPersistence {

	/**
	 * Constructor
	 */
	public PrecioproductoPersistenceJPA() {
		super(PrecioproductoEntity.class);
	}

	@Override
	public PrecioproductoEntity load( Integer idprecioproducto ) {
		return super.load( idprecioproducto );
	}

	@Override
	public boolean delete( Integer idprecioproducto ) {
		return super.delete( idprecioproducto );
	}

	@Override
	public boolean delete(PrecioproductoEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdprecioproducto() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PrecioproductoEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
