/*
 * Created on 4 oct 2016 ( Time 09:46:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.salondeventas.server.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.salondeventas.server.modelo.jpa.VentaEntity;
import org.salondeventas.server.persistence.commons.jpa.GenericJpaService;
import org.salondeventas.server.persistence.commons.jpa.JpaOperation;
import org.salondeventas.server.persistence.services.VentaPersistence;
import org.springframework.stereotype.Service;

/**
 * JPA implementation for basic persistence operations ( entity "Venta" )
 * 
 * @author Telosys Tools Generator
 *
 */
@Service("ventaDao")
public class VentaPersistenceJPA extends GenericJpaService<VentaEntity, Integer> implements VentaPersistence {

	/**
	 * Constructor
	 */
	public VentaPersistenceJPA() {
		super(VentaEntity.class);
	}

	@Override
	public VentaEntity load( Integer idventa ) {
		return super.load( idventa );
	}

	@Override
	public boolean delete( Integer idventa ) {
		return super.delete( idventa );
	}

	@Override
	public boolean delete(VentaEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdventa() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("VentaEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
