/*
 * Created on 31 oct 2016 ( Time 11:50:31 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.ConfiguracionEntity;

/**
 * Basic persistence operations for entity "Configuracion"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface ConfiguracionPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param configuracion
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(ConfiguracionEntity configuracion) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idconfiguracion
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idconfiguracion) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param configuracion
	 */
	public void insert(ConfiguracionEntity configuracion) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idconfiguracion
	 * @return the entity loaded (or null if not found)
	 */
	public ConfiguracionEntity load(Integer idconfiguracion) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<ConfiguracionEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<ConfiguracionEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<ConfiguracionEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param configuracion
	 * @return
	 */
	public ConfiguracionEntity save(ConfiguracionEntity configuracion) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<ConfiguracionEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
