/*
 * Created on 9 oct 2016 ( Time 00:06:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.EmpresaEntity;

/**
 * Basic persistence operations for entity "Empresa"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface EmpresaPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param empresa
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(EmpresaEntity empresa) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idempresa
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idempresa) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param empresa
	 */
	public void insert(EmpresaEntity empresa) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idempresa
	 * @return the entity loaded (or null if not found)
	 */
	public EmpresaEntity load(Integer idempresa) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<EmpresaEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<EmpresaEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<EmpresaEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param empresa
	 * @return
	 */
	public EmpresaEntity save(EmpresaEntity empresa) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<EmpresaEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
