/*
 * Created on 9 oct 2016 ( Time 00:06:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.LineadeventaEntity;
import org.salondeventas.server.modelo.jpa.LineadeventaEntityKey;

/**
 * Basic persistence operations for entity "Lineadeventa"
 * 
 * This Bean has a composite Primary Key : LineadeventaEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface LineadeventaPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param lineadeventa
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(LineadeventaEntity lineadeventa) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idlineadeventa
	 * @param idproducto
	 * @param idventa
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idlineadeventa, Integer idproducto, Integer idventa) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param lineadeventa
	 */
	public void insert(LineadeventaEntity lineadeventa) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idlineadeventa
	 * @param idproducto
	 * @param idventa
	 * @return the entity loaded (or null if not found)
	 */
	public LineadeventaEntity load(Integer idlineadeventa, Integer idproducto, Integer idventa) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<LineadeventaEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<LineadeventaEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<LineadeventaEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param lineadeventa
	 * @return
	 */
	public LineadeventaEntity save(LineadeventaEntity lineadeventa) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<LineadeventaEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();

	public LineadeventaEntity load(LineadeventaEntityKey key);
	
}
