/*
 * Created on 31 oct 2016 ( Time 11:50:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.PantallapermisosEntity;

/**
 * Basic persistence operations for entity "Pantallapermisos"
 * 
 * This Bean has a composite Primary Key : PantallapermisosEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface PantallapermisosPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pantallapermisos
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PantallapermisosEntity pantallapermisos) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idpantalla
	 * @param idpermiso
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idpantalla, String idpermiso) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pantallapermisos
	 */
	public void insert(PantallapermisosEntity pantallapermisos) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idpantalla
	 * @param idpermiso
	 * @return the entity loaded (or null if not found)
	 */
	public PantallapermisosEntity load(Integer idpantalla, String idpermiso) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PantallapermisosEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PantallapermisosEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PantallapermisosEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param pantallapermisos
	 * @return
	 */
	public PantallapermisosEntity save(PantallapermisosEntity pantallapermisos) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PantallapermisosEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
