/*
 * Created on 31 oct 2016 ( Time 11:50:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.PerfilespantallasEntity;

/**
 * Basic persistence operations for entity "Perfilespantallas"
 * 
 * This Bean has a composite Primary Key : PerfilespantallasEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface PerfilespantallasPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param perfilespantallas
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PerfilespantallasEntity perfilespantallas) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idperfiles
	 * @param idpantallas
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idperfiles, Integer idpantallas) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param perfilespantallas
	 */
	public void insert(PerfilespantallasEntity perfilespantallas) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idperfiles
	 * @param idpantallas
	 * @return the entity loaded (or null if not found)
	 */
	public PerfilespantallasEntity load(Integer idperfiles, Integer idpantallas) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PerfilespantallasEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PerfilespantallasEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PerfilespantallasEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param perfilespantallas
	 * @return
	 */
	public PerfilespantallasEntity save(PerfilespantallasEntity perfilespantallas) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PerfilespantallasEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
