/*
 * Created on 31 oct 2016 ( Time 11:50:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.PerfilesEntity;

/**
 * Basic persistence operations for entity "Perfiles"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface PerfilesPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param perfiles
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PerfilesEntity perfiles) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idperfiles
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idperfiles) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param perfiles
	 */
	public void insert(PerfilesEntity perfiles) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idperfiles
	 * @return the entity loaded (or null if not found)
	 */
	public PerfilesEntity load(Integer idperfiles) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PerfilesEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PerfilesEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PerfilesEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param perfiles
	 * @return
	 */
	public PerfilesEntity save(PerfilesEntity perfiles) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PerfilesEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
