/*
 * Created on 31 oct 2016 ( Time 11:50:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.PermisoEntity;

/**
 * Basic persistence operations for entity "Permiso"
 * 
 * This Bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface PermisoPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param permiso
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PermisoEntity permiso) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idpermiso
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String idpermiso) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param permiso
	 */
	public void insert(PermisoEntity permiso) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idpermiso
	 * @return the entity loaded (or null if not found)
	 */
	public PermisoEntity load(String idpermiso) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PermisoEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PermisoEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PermisoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param permiso
	 * @return
	 */
	public PermisoEntity save(PermisoEntity permiso) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PermisoEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
