/*
 * Created on 9 oct 2016 ( Time 00:06:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.PrecioproductoEntity;
import org.salondeventas.server.modelo.jpa.PrecioproductoEntityKey;

/**
 * Basic persistence operations for entity "Precioproducto"
 * 
 * This Bean has a composite Primary Key : PrecioproductoEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface PrecioproductoPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param precioproducto
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(PrecioproductoEntity precioproducto) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idprecioproducto
	 * @param idproducto
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idprecioproducto, Integer idproducto) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param precioproducto
	 */
	public void insert(PrecioproductoEntity precioproducto) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idprecioproducto
	 * @param idproducto
	 * @return the entity loaded (or null if not found)
	 */
	public PrecioproductoEntity load(Integer idprecioproducto, Integer idproducto) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<PrecioproductoEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<PrecioproductoEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<PrecioproductoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param precioproducto
	 * @return
	 */
	public PrecioproductoEntity save(PrecioproductoEntity precioproducto) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<PrecioproductoEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();

	public PrecioproductoEntity load(PrecioproductoEntityKey key);
	
}
