/*
 * Created on 22 nov 2016 ( Time 09:10:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.ProductoIngresoEntity;

/**
 * Basic persistence operations for entity "ProductoIngreso"
 * 
 * This Bean has a composite Primary Key : ProductoIngresoEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface ProductoIngresoPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param productoIngreso
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(ProductoIngresoEntity productoIngreso) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idproductoIngreso
	 * @param idproducto
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idproductoIngreso, Integer idproducto) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param productoIngreso
	 */
	public void insert(ProductoIngresoEntity productoIngreso) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idproductoIngreso
	 * @param idproducto
	 * @return the entity loaded (or null if not found)
	 */
	public ProductoIngresoEntity load(Integer idproductoIngreso, Integer idproducto) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<ProductoIngresoEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<ProductoIngresoEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<ProductoIngresoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param productoIngreso
	 * @return
	 */
	public ProductoIngresoEntity save(ProductoIngresoEntity productoIngreso) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<ProductoIngresoEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
