/*
 * Created on 31 oct 2016 ( Time 11:50:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;

import org.salondeventas.server.modelo.jpa.UsuarioperfilesEntity;

/**
 * Basic persistence operations for entity "Usuarioperfiles"
 * 
 * This Bean has a composite Primary Key : UsuarioperfilesEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface UsuarioperfilesPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param usuarioperfiles
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(UsuarioperfilesEntity usuarioperfiles) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idusuario
	 * @param idperfil
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idusuario, Integer idperfil) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param usuarioperfiles
	 */
	public void insert(UsuarioperfilesEntity usuarioperfiles) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idusuario
	 * @param idperfil
	 * @return the entity loaded (or null if not found)
	 */
	public UsuarioperfilesEntity load(Integer idusuario, Integer idperfil) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<UsuarioperfilesEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<UsuarioperfilesEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<UsuarioperfilesEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param usuarioperfiles
	 * @return
	 */
	public UsuarioperfilesEntity save(UsuarioperfilesEntity usuarioperfiles) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<UsuarioperfilesEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
