/*
 * Created on 20 nov 2016 ( Time 10:16:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;
import java.util.Map;
import org.salondeventas.server.modelo.informe.jpa.VCantProdVendidosEntity;

public interface VCantProdVendidosPersistence {

	public List<VCantProdVendidosEntity> loadAll() ;

	public List<VCantProdVendidosEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<VCantProdVendidosEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;
	
	public List<VCantProdVendidosEntity> search( Map<String, Object> criteria ) ;

	public long countAll();
	
}
