/*
 * Created on 9 oct 2016 ( Time 02:02:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.services.persistence;

import java.util.List;

import org.salondeventas.server.modelo.jpa.VproductosEntity;

/**
 * Basic persistence operations for entity "Producto"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface VProductoPersistence {
	
	public List<VproductosEntity> loadAll() ;
	
}
