/*
 * Created on 9 oct 2016 ( Time 02:32:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.test.persistence;


import org.salondeventas.server.modelo.jpa.PrecioproductoEntity;
import org.salondeventas.server.mock.PrecioproductoEntityMock;
import org.salondeventas.server.services.persistence.commons.jpa.PersistenceServiceProvider;
import org.salondeventas.server.services.persistence.PrecioproductoPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Precioproducto persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class PrecioproductoPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		PrecioproductoPersistence service = PersistenceServiceProvider.getService(PrecioproductoPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Precioproducto persistence : delete + load ..." );
		
		PrecioproductoPersistence service = PersistenceServiceProvider.getService(PrecioproductoPersistence.class);
		
		PrecioproductoEntityMock mock = new PrecioproductoEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0 , 0  );
		// process( service, mock, ... );
	}

	private void process(PrecioproductoPersistence service, PrecioproductoEntityMock mock, Integer idprecioproducto, Integer idproducto ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		PrecioproductoEntity entity = service.load( idprecioproducto, idproducto );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idprecioproducto, idproducto ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Producto
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idprecioproducto, idproducto );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
