/*
 * Created on 9 oct 2016 ( Time 02:32:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.server.test.persistence;


import org.salondeventas.server.modelo.jpa.UsuarioEntity;
import org.salondeventas.server.mock.UsuarioEntityMock;
import org.salondeventas.server.services.persistence.commons.jpa.PersistenceServiceProvider;
import org.salondeventas.server.services.persistence.UsuarioPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Usuario persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class UsuarioPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		UsuarioPersistence service = PersistenceServiceProvider.getService(UsuarioPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Usuario persistence : delete + load ..." );
		
		UsuarioPersistence service = PersistenceServiceProvider.getService(UsuarioPersistence.class);
		
		UsuarioEntityMock mock = new UsuarioEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(UsuarioPersistence service, UsuarioEntityMock mock, Integer idusuario ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		UsuarioEntity entity = service.load( idusuario );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idusuario ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idusuario );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
